"""add is_active to PlayerModel

Revision ID: 54b9505a6fa0
Revises: 733f2b27756e
Create Date: 2025-07-16 13:50:37.472623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b9505a6fa0'
down_revision: Union[str, Sequence[str], None] = '733f2b27756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'is_active')
    # ### end Alembic commands ###
