"""Add users table and user_id to players for persistent user registration and multi-game support

Revision ID: 96b2d411a647
Revises: 75b478146d0a
Create Date: 2025-07-15 16:55:24.630052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b2d411a647'
down_revision: Union[str, Sequence[str], None] = '75b478146d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'user_id')
    # ### end Alembic commands ###
