"""Add game snapshots with phase tracking

Revision ID: c7be50acda93
Revises: ac6a8bd4ac64
Create Date: 2025-10-02 19:34:49.230020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7be50acda93'
down_revision: Union[str, Sequence[str], None] = 'ac6a8bd4ac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('phase_code', sa.String(), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('map_image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_snapshots_game_id'), 'game_snapshots', ['game_id'], unique=False)
    op.create_index('ix_snapshots_created_at', 'game_snapshots', ['created_at'], unique=False)
    op.create_index('ix_snapshots_game_phase', 'game_snapshots', ['game_id', 'phase_code'], unique=False)
    op.create_index('ix_snapshots_game_turn', 'game_snapshots', ['game_id', 'turn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_game_turn', table_name='game_snapshots')
    op.drop_index('ix_snapshots_game_phase', table_name='game_snapshots')
    op.drop_index('ix_snapshots_created_at', table_name='game_snapshots')
    op.drop_index(op.f('ix_game_snapshots_game_id'), table_name='game_snapshots')
    op.drop_table('game_snapshots')
    # ### end Alembic commands ###
