services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: diplomacy
      POSTGRES_PASSWORD: diplomacy
      POSTGRES_DB: diplomacy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      - DIPLOMACY_API_URL=http://localhost:8000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://diplomacy:diplomacy@db:5432/diplomacy
    ports:
      - "8000:8000"
    volumes:
      - ./new_implementation:/app/new_implementation
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    restart: always
    command: ["/app/start.sh"]

volumes:
  pgdata: 