"""add_missing_columns_and_indexes

Revision ID: 364890b0d05e
Revises: c7be50acda93
Create Date: 2025-10-17 19:57:34.241332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364890b0d05e'
down_revision: Union[str, Sequence[str], None] = 'c7be50acda93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_history_game_id'), 'game_history', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_history_phase'), 'game_history', ['phase'], unique=False)
    op.create_index(op.f('ix_game_history_timestamp'), 'game_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_game_history_turn'), 'game_history', ['turn'], unique=False)
    op.create_index('ix_history_game_phase', 'game_history', ['game_id', 'phase'], unique=False)
    op.create_index('ix_history_game_turn', 'game_history', ['game_id', 'turn'], unique=False)
    op.create_index('ix_history_timestamp_desc', 'game_history', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_history_turn_timestamp', 'game_history', ['turn', 'timestamp'], unique=False)
    op.create_index('ix_games_active_deadline', 'games', ['is_active', 'deadline'], unique=False)
    op.create_index(op.f('ix_games_deadline'), 'games', ['deadline'], unique=False)
    op.create_index(op.f('ix_games_is_active'), 'games', ['is_active'], unique=False)
    op.create_index('ix_games_map_active', 'games', ['map_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_games_map_name'), 'games', ['map_name'], unique=False)
    op.add_column('messages', sa.Column('recipient_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_game_id'), 'messages', ['game_id'], unique=False)
    op.create_index('ix_messages_game_recipient', 'messages', ['game_id', 'recipient_power'], unique=False)
    op.create_index('ix_messages_game_timestamp', 'messages', ['game_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_recipient_power'), 'messages', ['recipient_power'], unique=False)
    op.create_index('ix_messages_recipient_timestamp', 'messages', ['recipient_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_recipient_user_id'), 'messages', ['recipient_user_id'], unique=False)
    op.create_index('ix_messages_sender_timestamp', 'messages', ['sender_user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_index('ix_messages_timestamp_desc', 'messages', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['recipient_user_id'], ['id'])
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_order_text'), 'orders', ['order_text'], unique=False)
    op.create_index('ix_orders_player_created', 'orders', ['player_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_turn'), 'orders', ['turn'], unique=False)
    op.create_index('ix_orders_turn_created', 'orders', ['turn', 'created_at'], unique=False)
    op.create_index('ix_players_game_active', 'players', ['game_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_players_is_active'), 'players', ['is_active'], unique=False)
    op.create_index('ix_players_power_active', 'players', ['power', 'is_active'], unique=False)
    op.create_index(op.f('ix_players_telegram_id'), 'players', ['telegram_id'], unique=False)
    op.create_index('ix_players_user_active', 'players', ['user_id', 'is_active'], unique=False)
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_players_user_active', table_name='players')
    op.drop_index(op.f('ix_players_telegram_id'), table_name='players')
    op.drop_index('ix_players_power_active', table_name='players')
    op.drop_index(op.f('ix_players_is_active'), table_name='players')
    op.drop_index('ix_players_game_active', table_name='players')
    op.drop_index('ix_orders_turn_created', table_name='orders')
    op.drop_index(op.f('ix_orders_turn'), table_name='orders')
    op.drop_index('ix_orders_player_created', table_name='orders')
    op.drop_index(op.f('ix_orders_order_text'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_column('orders', 'created_at')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('ix_messages_timestamp_desc', table_name='messages')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.drop_index('ix_messages_sender_timestamp', table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_user_id'), table_name='messages')
    op.drop_index('ix_messages_recipient_timestamp', table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_power'), table_name='messages')
    op.drop_index('ix_messages_game_timestamp', table_name='messages')
    op.drop_index('ix_messages_game_recipient', table_name='messages')
    op.drop_index(op.f('ix_messages_game_id'), table_name='messages')
    op.drop_column('messages', 'recipient_user_id')
    op.drop_index(op.f('ix_games_map_name'), table_name='games')
    op.drop_index('ix_games_map_active', table_name='games')
    op.drop_index(op.f('ix_games_is_active'), table_name='games')
    op.drop_index(op.f('ix_games_deadline'), table_name='games')
    op.drop_index('ix_games_active_deadline', table_name='games')
    op.drop_index('ix_history_turn_timestamp', table_name='game_history')
    op.drop_index('ix_history_timestamp_desc', table_name='game_history')
    op.drop_index('ix_history_game_turn', table_name='game_history')
    op.drop_index('ix_history_game_phase', table_name='game_history')
    op.drop_index(op.f('ix_game_history_turn'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_timestamp'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_phase'), table_name='game_history')
    op.drop_index(op.f('ix_game_history_game_id'), table_name='game_history')
    # ### end Alembic commands ###
