"""add indexes for performance optimization

Revision ID: 733f2b27756e
Revises: 3adfaf26eded
Create Date: 2025-07-15 19:19:04.937929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733f2b27756e'
down_revision: Union[str, Sequence[str], None] = '3adfaf26eded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_player_id'), 'orders', ['player_id'], unique=False)
    op.create_index('ix_orders_player_id_turn', 'orders', ['player_id', 'turn'], unique=False)
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    op.create_index('ix_players_game_id_power', 'players', ['game_id', 'power'], unique=False)
    op.create_index('ix_players_game_id_user_id', 'players', ['game_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_players_power'), 'players', ['power'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_power'), table_name='players')
    op.drop_index('ix_players_game_id_user_id', table_name='players')
    op.drop_index('ix_players_game_id_power', table_name='players')
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_index('ix_orders_player_id_turn', table_name='orders')
    op.drop_index(op.f('ix_orders_player_id'), table_name='orders')
    # ### end Alembic commands ###
